version: '3.8'

services:
  db:
    image: postgres:15
    restart: unless-stopped
    environment:
      POSTGRES_USER: simplify
      POSTGRES_PASSWORD: simplify
      POSTGRES_DB: simplify
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U simplify"]
      interval: 10s
      timeout: 5s
      retries: 5

  api:
    build:
      context: ./api
    environment:
      NODE_ENV: production
      PORT: 3000
      DB_HOST: db
      DB_PORT: 5432
      DB_USERNAME: simplify
      DB_PASSWORD: simplify
      DB_DATABASE: simplify
      JWT_SECRET: "localdevsecret"
      SENTRY_DSN: "${SENTRY_DSN:-}" # Set this in your .env for Sentry
    ports:
      - "3000:3000"
    depends_on:
      db:
        condition: service_healthy

  web:
    build:
      context: ./apps/web
    environment:
      NODE_ENV: production
      API_URL: http://api:3000
      PORT: 3001
      SENTRY_DSN: "${SENTRY_DSN:-}"
      NEXT_PUBLIC_SENTRY_DSN: "${NEXT_PUBLIC_SENTRY_DSN:-}"
    ports:
      - "3001:3000"
    depends_on:
      - api